on: push
name: Lint markdown
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: lots0logs/gh-action-get-changed-files@v1.0.2
    - name: My step name
      run: |
        import os 

        print('Hello Github actions world')
        print('Second line')
        print(os.environ['PATH'])
        for f in os.listdir("."):
          print(f)
      shell: python
        