on: push
name: Lint markdown
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: My step name
      run: |
        import os 
        import json

        def readJson(path) :
          with open(path) as json_file:
            data = json.load(json_file)
            return data
        print(os.environ['PATH'])
        for f in os.listdir("."):
          print(f)
        path = os.environ['GITHUB_EVENT_PATH']
        print('Event path is %s' % path)
        event = readJson(path)
        url = event['head_commit']['url']
        print('HEAD is at %s' % url)
      shell: python
        