on: push
name: Lint markdown
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest  
    steps:
    - name: My step name
      run: print('Hello Github actions world')
      shell: python
      