on:
  push:
name: Lint markdown
jobs:
  lintMarkdownFiles:
    name: Lint markdown files
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
    - uses: actions/checkout@master
    - name: Lint markdown files
    