on: push
name: Lint markdown
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest  
    steps:
    - name: My step name
    - uses: actions/checkout@v1
    run: |
      import os 

      print('Hello Github actions world')
      print('Second line')
      print(os.environ['PATH'])
    shell: python
        