on: push
name: Lint markdown
jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest  
    steps:
    - name: My step name
      shell: python
      run: |
        import os 
        import argparse 

        print(f"Hello Github actions world")
