on:
  push:
name: Lint markdown
jobs:
  lintMarkdownFiles:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lint markdown files
      uses: docker://cdssnc/markdown-lint